server/src/main/java/org/gluu/oxtrust/action/WhitePagesAction.java
/*
 * oxTrust is available under the MIT License (2008). See http://opensource.org/licenses/MIT for full text.
 *
 * Copyright (c) 2014, Gluu
 */

package org.gluu.oxtrust.action;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Set;

import javax.annotation.PostConstruct;
import javax.enterprise.context.ConversationScoped;
import javax.faces.application.FacesMessage;
import javax.inject.Inject;
import javax.inject.Named;

import org.gluu.jsf2.message.FacesMessages;
import org.gluu.jsf2.service.ConversationService;
import org.gluu.model.GluuAttribute;
import org.gluu.model.GluuUserRole;
import org.gluu.oxtrust.model.GluuCustomAttribute;
import org.gluu.oxtrust.model.GluuCustomPerson;
import org.gluu.oxtrust.service.AttributeService;
import org.gluu.oxtrust.service.PersonService;
import org.gluu.oxtrust.util.OxTrustConstants;
import org.gluu.service.security.Secure;
import org.slf4j.Logger;

/**
 * Action class for view white pages
 * 
 * @author Yuriy Movchan Date: 11.02.2010
 */
@Named("whitePagesAction")
@ConversationScoped
@Secure("#{permissionService.hasPermission('profile', 'access')}")
public class WhitePagesAction implements Serializable {

	private static final long serialVersionUID = 6730313815008211305L;

	private List<String> tableAttributes;

	@Inject
	private Logger log;

	@Inject
	private FacesMessages facesMessages;

	@Inject
	private ConversationService conversationService;

	@Inject
	private AttributeService attributeService;

	@Inject
	private PersonService personService;

	private String tableState;

	private List<GluuCustomPerson> persons;
	private Set<Integer> selectedPersons;

	@PostConstruct
	public void init() {
		this.tableAttributes = Arrays.asList("cn", "photo1", "mail", "phone");
	}

	@Secure("#{permissionService.hasPermission(configurationService.configuration, 'whitePagesEnabled')}")
	public String start() {
		if (persons != null) {
			return OxTrustConstants.RESULT_SUCCESS;
		}

		return search();
	}

	@Secure("#{permissionService.hasPermission(configurationService.configuration, 'whitePagesEnabled')}")
	public String search() {
		try {
			GluuCustomPerson person = new GluuCustomPerson();
			person.setGluuAllowPublication("true");
			this.persons = personService.findPersons(person, 0);
		} catch (Exception ex) {
			log.error("Failed to find persons", ex);

			facesMessages.add(FacesMessage.SEVERITY_ERROR, "Failed to find persons white pages");
			conversationService.endConversation();

			return OxTrustConstants.RESULT_FAILURE;
		}

		return OxTrustConstants.RESULT_SUCCESS;
	}

	public List<GluuCustomPerson> getPersons() {
		return persons;
	}

	public String getTableState() {
		return tableState;
	}

	public void setTableState(String tableState) {
		this.tableState = tableState;
	}

	public Set<Integer> getSelectedPersons() {
		return selectedPersons;
	}

	public void setSelectedPersons(Set<Integer> selectedPersons) {
		this.selectedPersons = selectedPersons;
	}

	public GluuCustomPerson getSelectedPerson() {
		if ((this.selectedPersons == null) || (this.selectedPersons.isEmpty())) {
			return null;
		} else {
			int index = this.selectedPersons.iterator().next();
			return this.persons.get(index);
		}
	}

	public List<GluuCustomAttribute> getReleasedAttributes(GluuCustomPerson person) {
		if (person == null) {
			return Arrays.asList(new GluuCustomAttribute[0]);
		}

		List<GluuCustomAttribute> releasedAttributes = new ArrayList<GluuCustomAttribute>();
		for (GluuCustomAttribute attribute : person.getCustomAttributes()) {
			List<GluuAttribute> attributes = attributeService.getAllPersonAttributes(GluuUserRole.USER);
			GluuAttribute metadata = attributeService.getAttributeByName(attribute.getName(), attributes);
			if (metadata != null && metadata.isWhitePagesCanView() && !tableAttributes.contains(attribute.getName())) {
				attribute.setMetadata(metadata);
				releasedAttributes.add(attribute);
			}
		}

		return releasedAttributes;
	}

	public boolean released(GluuCustomPerson person, String attributeName) {
		return person.getGluuOptOuts() == null || !person.getGluuOptOuts().contains(attributeName);
	}

	public boolean canContact(GluuCustomPerson person) {
		return false;
	}
}

server/src/main/webapp/whitePage/viewWhitePages.xhtml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:a4j="http://richfaces.org/a4j"
                xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:rich="http://richfaces.org/rich"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets" template="/WEB-INF/incl/layout/newtemplate.xhtml">
    <f:metadata>
        <f:viewAction action="#{conversationService.initConversation}"/>
        <f:viewAction action="#{whitePagesAction.start}"
                      if="#{whitePagesAction.persons == null}"
                      onPostback="false"/>
    </f:metadata>

    <ui:define name="body">
        <section class="content-header">
            <h1 style="color: #333;">
                #{msgs['whitePages.whitePages']}
                <small>
                    <i class="fa fa-caret-right" style="color: #333 !important;"/>#{msgs['whitePages.view']}</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    <a href="#{request.contextPath}/home.htm">
                        <i class="fa fa-home"/>#{msgs['whitePages.whitePages']}</a>
                </li>
                <li class="organization/configuration">#{msgs['whitePages.view']}</li>
            </ol>
        </section>
        <section class="content">
            <div id="formArea">
                <a4j:queue size="1"/>
                <h:outputText value="#{msgs['whitePages.whitePages']}"/>

                <h:form id="form">
                    <h:panelGrid columnClasses="alignTop, alignTop" columns="2">

                        <rich:extendedDataTable id="table" selection="#{whitePagesAction.selectedPersons}"
                                                selectionMode="single" sortMode="multi" style="width:100%;"
                                                styleClass="rf-dt data sortable"
                                                tableState="#{whitePagesAction.tableState}"
                                                value="#{whitePagesAction.persons}" var="entry" width="563px">
                            <rich:column id="col_1" label="Photo" sortable="false" width="53px">
                                <f:facet name="header">
                                    <h:outputText value="#{msgs['whitePages.photo']}"/>
                                </f:facet>
                                <h:graphicImage value="#{whitePagesAction.getPhotoThumbData(entry)}" width="45px"/>
                            </rich:column>
                            <rich:column filterBy="#{entry.getAttribute('cn')}" filterEvent="onkeyup" id="col_2"
                                         label="#{msgs['whitePages.name']}" sortBy="#{entry.getAttribute('cn')}"
                                         sortable="true" width="170px">
                                <f:facet name="header">
                                    <h:outputText value="#{msgs['whitePages.name']}"/>
                                </f:facet>
                                <h:outputText id="entry_name" value="#{entry.getAttribute('cn')}"/>
                            </rich:column>
                            <rich:column filterBy="#{entry.getAttribute('mail')}" filterEvent="onkeyup" id="col_3"
                                         label="E-Mail" sortBy="#{entry.getAttribute('mail')}" sortable="true"
                                         width="170px">
                                <f:facet name="header">
                                    <h:outputText value="#{msgs['whitePages.email']}"/>
                                </f:facet>
                                <h:outputText id="entry_email" rendered="#{whitePagesAction.released(entry, 'mail')}"
                                              value="#{entry.getAttribute('mail')}"/>
                            </rich:column>
                            <rich:column filterBy="#{entry.getAttribute('telephoneNumber')}" filterEvent="onkeyup"
                                         id="col_4" label="#{msgs['whitePages.phoneNumber']}"
                                         sortBy="#{entry.getAttribute('telephoneNumber')}" sortable="true"
                                         width="170px">
                                <f:facet name="header">
                                    <h:outputText value="#{msgs['whitePages.phoneNumber']}"/>
                                </f:facet>
                                <h:outputText id="entry_phone"
                                              rendered="#{whitePagesAction.released(entry, 'telephoneNumber')}"
                                              value="#{entry.getAttribute('telephoneNumber')}"/>
                            </rich:column>
                            <a4j:ajax event="selectionchange" execute="@this" limitRender="true"
                                      render="selectiontable"/>
                        </rich:extendedDataTable>

                        <h:panelGrid id="selectiontable">
                            <ui:param name="sel" value="#{whitePagesAction.selectedPerson}"/>
                            <h:panelGroup layout="block" rendered="#{sel ne null}" style="width:300px">
                                <rich:panel>
                                    <f:facet name="header">
                                        <h:outputText value="#{sel.getAttribute('cn')}"/>
                                    </f:facet>

                                    <h:graphicImage value="#{whitePagesAction.getPhotoThumbData(sel)}" width="275px"/>
                                    <h:panelGrid columns="1">
                                        <h:panelGroup>
                                            <h:outputText styleClass="name" value="#{msgs['whitePages.name']} "/>
                                            <h:outputText value="#{sel.getAttribute('cn')}"/>
                                        </h:panelGroup>
                                        <h:panelGroup
                                                rendered="#{(sel.getAttribute('mail') ne null) and whitePagesAction.released(sel, 'mail')}">
                                            <h:outputText styleClass="name" value="#{msgs['whitePages.email']} "/>
                                            <h:outputText value="#{sel.getAttribute('mail')}"/>
                                        </h:panelGroup>
                                        <h:panelGroup
                                                rendered="#{(sel.getAttribute('telephoneNumber') ne null) and whitePagesAction.released(sel, 'telephoneNumber')}">
                                            <h:outputText styleClass="name" value="#{msgs['whitePages.phone']} "/>
                                            <h:outputText value="#{sel.getAttribute('telephoneNumber')}"/>
                                        </h:panelGroup>

                                        <a4j:repeat value="#{whitePagesAction.getReleasedAttributes(sel)}"
                                                    var="_custAttr">
                                            <h:panelGroup
                                                    rendered="#{(_custAttr ne null) and whitePagesAction.released(sel, _custAttr.metadata.name)}">
                                                <h:outputText styleClass="name"
                                                              value="#{_custAttr.metadata.displayName} "/>
                                                <h:outputText value="#{_custAttr.value}"/>
                                            </h:panelGroup>
                                        </a4j:repeat>
                                    </h:panelGrid>
                                </rich:panel>
                            </h:panelGroup>
                        </h:panelGrid>
                    </h:panelGrid>
                </h:form>
            </div>
        </section>
    </ui:define>
</ui:composition>