server/src/main/java/org/gluu/oxtrust/action/ConfigureLogViewerAction.java
/*
 * oxTrust is available under the MIT License (2008). See http://opensource.org/licenses/MIT for full text.
 *
 * Copyright (c) 2014, Gluu
 */

package org.gluu.oxtrust.action;

import java.io.IOException;
import java.io.Serializable;
import java.util.List;

import javax.enterprise.context.ConversationScoped;
import javax.faces.application.FacesMessage;
import javax.inject.Inject;
import javax.inject.Named;

import org.gluu.jsf2.message.FacesMessages;
import org.gluu.jsf2.service.ConversationService;
import org.gluu.model.SimpleCustomProperty;
import org.gluu.oxauth.model.configuration.AppConfiguration;
import org.gluu.oxtrust.model.GluuConfiguration;
import org.gluu.oxtrust.model.LogViewerConfig;
import org.gluu.oxtrust.model.SimpleCustomPropertiesListModel;
import org.gluu.oxtrust.service.ConfigurationService;
import org.gluu.oxtrust.service.JsonConfigurationService;
import org.gluu.oxtrust.service.logger.LoggerService;
import org.gluu.oxtrust.util.OxTrustConstants;
import org.gluu.service.security.Secure;
import org.slf4j.Logger;

/**
 * Action class for configuring log viewer
 *
 * @author Yuriy Movchan Date: 07/08/2013
 */
@Named("configureLogViewerAction")
@ConversationScoped
@Secure("#{permissionService.hasPermission('configuration', 'access')}")
public class ConfigureLogViewerAction implements SimpleCustomPropertiesListModel, Serializable {

	private static final long serialVersionUID = -3310460481895022468L;

	@Inject
	private Logger log;

	@Inject
	private ConfigurationService configurationService;

	@Inject
	private FacesMessages facesMessages;

	@Inject
	private ConversationService conversationService;

	@Inject
	private LoggerService loggerService;

	@Inject
	private JsonConfigurationService jsonConfigurationService;

	private GluuConfiguration configuration;

	private GluuConfiguration gluuServerDetail;

	private String oxTrustLogConfigLocation;
	private String oxAuthLogConfigLocation;

	private LogViewerConfig logViewerConfiguration;

	private boolean initialized;

	public String init() {
		if (this.logViewerConfiguration != null) {
			return OxTrustConstants.RESULT_SUCCESS;
		}

		this.configuration = configurationService.getConfiguration();
		this.gluuServerDetail = configurationService.getConfiguration();
		this.oxTrustLogConfigLocation = gluuServerDetail.getOxLogConfigLocation();

		try {
			this.oxAuthLogConfigLocation = jsonConfigurationService.getOxauthAppConfiguration()
					.getExternalLoggerConfiguration();
		} catch (Exception e) {
			log.error("Failed to retrieve oxauth configuration", e);
		}

		initConfigurations();

		this.initialized = true;

		return OxTrustConstants.RESULT_SUCCESS;
	}

	private void initConfigurations() {
		this.logViewerConfiguration = prepareLogViewerConfig();
	}

	public String update() {
		if (!validateLists()) {
			facesMessages.add(FacesMessage.SEVERITY_ERROR, "Failed to update log viewer configuration");
			return OxTrustConstants.RESULT_FAILURE;
		}

		updateConfiguration();
		updateOxAuthConfiguration();

		facesMessages.add(FacesMessage.SEVERITY_INFO, "Log viewer configuration updated");

		return OxTrustConstants.RESULT_SUCCESS;
	}

	private void updateConfiguration() {
		GluuConfiguration updateConfiguration = configurationService.getConfiguration();
		try {
			updateConfiguration.setOxLogViewerConfig(logViewerConfiguration);
			updateConfiguration.setOxLogConfigLocation(oxTrustLogConfigLocation);
			configurationService.updateConfiguration(updateConfiguration);
			loggerService.resetLoggerConfigLocation();
		} catch (Exception ex) {
			log.error("Failed to save log viewer configuration '{}'", ex);
		}
	}

	private void updateOxAuthConfiguration() {
		try {
			AppConfiguration appConfiguration = jsonConfigurationService.getOxauthAppConfiguration();
			appConfiguration.setExternalLoggerConfiguration(oxAuthLogConfigLocation);
			jsonConfigurationService.saveOxAuthAppConfiguration(appConfiguration);
		} catch (IOException e) {
			log.error("Failed to update oxauth-config.json", e);
			facesMessages.add(FacesMessage.SEVERITY_ERROR, "Failed to update oxAuth configuration in LDAP");
		}
	}

	private boolean validateLists() {
		boolean result = true;

		return result;
	}

	public String cancel() {
		facesMessages.add(FacesMessage.SEVERITY_INFO, "Log viewer configuration update were canceled");
		conversationService.endConversation();

		return OxTrustConstants.RESULT_SUCCESS;
	}

	private LogViewerConfig prepareLogViewerConfig() {
		LogViewerConfig logViewerConfig = configuration.getOxLogViewerConfig();

		if (logViewerConfig == null) {
			logViewerConfig = new LogViewerConfig();
		}

		return logViewerConfig;
	}

	public boolean isInitialized() {
		return initialized;
	}

	@Override
	public void addItemToSimpleCustomProperties(List<SimpleCustomProperty> simpleCustomProperties) {
		if (simpleCustomProperties != null) {
			simpleCustomProperties.add(new SimpleCustomProperty("description", ""));
		}
	}

	@Override
	public void removeItemFromSimpleCustomProperties(List<SimpleCustomProperty> simpleCustomProperties,
			SimpleCustomProperty simpleCustomProperty) {
		if (simpleCustomProperties != null) {
			simpleCustomProperties.remove(simpleCustomProperty);
		}
	}

	public LogViewerConfig getLogViewerConfiguration() {
		return logViewerConfiguration;
	}

	public String getOxTrustLogConfigLocation() {
		return oxTrustLogConfigLocation;
	}

	public void setOxTrustLogConfigLocation(String oxTrustLogConfigLocation) {
		this.oxTrustLogConfigLocation = oxTrustLogConfigLocation;
	}

	public String getOxAuthLogConfigLocation() {
		return oxAuthLogConfigLocation;
	}

	public void setOxAuthLogConfigLocation(String oxAuthLogConfigLocation) {
		this.oxAuthLogConfigLocation = oxAuthLogConfigLocation;
	}
}

server/src/main/java/org/gluu/oxtrust/action/ViewLogFileAction.java
/*
 * oxTrust is available under the MIT License (2008). See http://opensource.org/licenses/MIT for full text.
 *
 * Copyright (c) 2014, Gluu
 */

package org.gluu.oxtrust.action;

import java.io.File;
import java.io.FileFilter;
import java.io.IOException;
import java.io.Serializable;
import java.nio.charset.Charset;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.enterprise.context.ConversationScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.commons.io.FilenameUtils;
import org.apache.commons.io.filefilter.AndFileFilter;
import org.apache.commons.io.filefilter.FileFileFilter;
import org.apache.commons.io.filefilter.WildcardFileFilter;
import org.gluu.model.SimpleCustomProperty;
import org.gluu.oxtrust.model.GluuConfiguration;
import org.gluu.oxtrust.model.LogViewerConfig;
import org.gluu.oxtrust.service.ConfigurationService;
import org.gluu.oxtrust.util.OxTrustConstants;
import org.gluu.service.security.Secure;
import org.gluu.util.StringHelper;
import org.gluu.util.io.ReverseLineReader;
import org.slf4j.Logger;

/**
 * Action class for configuring log viewer
 * 
 * @author Yuriy Movchan Date: 07/08/2013
 */
@ConversationScoped
@Named
@Secure("#{permissionService.hasPermission('log', 'access')}")
public class ViewLogFileAction implements Serializable {

	private static final long serialVersionUID = -3310340481895022468L;

	@Inject
	private Logger log;
	
	@Inject
	private ConfigurationService configurationService;

	private GluuConfiguration configuration;

	private LogViewerConfig logViewerConfiguration;
	private Map<Integer, String> logFiles;

	private boolean initialized;

	private int activeLogFileIndex;
	
	private String currentLogFileName="";

	private int displayLastLinesCount;

	public String init() {
		if (this.logViewerConfiguration != null) {
			return OxTrustConstants.RESULT_SUCCESS;
		}

		this.configuration = configurationService.getConfiguration();

		initConfigurations();
		
		this.activeLogFileIndex = -1;
		
		this.displayLastLinesCount = 400;
		this.initialized = true;

		return OxTrustConstants.RESULT_SUCCESS;
	}

	private void initConfigurations() {
		this.logViewerConfiguration = prepareLogViewerConfig();

		this.logFiles = prepareLogFiles();
	}

	private LogViewerConfig prepareLogViewerConfig() {
		LogViewerConfig logViewerConfig = configuration.getOxLogViewerConfig();

		if (logViewerConfig == null) {
			logViewerConfig = new LogViewerConfig();
		}

		return logViewerConfig;
	}

	private Map<Integer, String> prepareLogFiles() {
		Map<Integer, String> logFiles = new HashMap<Integer, String>();

		int fileIndex = 0;
		for (SimpleCustomProperty logTemplate : this.logViewerConfiguration.getLogTemplates()) {
			String logTemplatePattern = logTemplate.getValue2();
			if (StringHelper.isEmpty(logTemplatePattern)) {
				continue;
			}

			String logTemplatePath = FilenameUtils.getFullPath(logTemplatePattern);
			String logTemplateFile = FilenameUtils.getName(logTemplatePattern);

			File logTemplateBaseDir = new File(logTemplatePath);

			FileFilter fileFilter = new AndFileFilter(FileFileFilter.FILE, new WildcardFileFilter(logTemplateFile));
			File[] files = logTemplateBaseDir.listFiles(fileFilter);
			if (files == null) {
				continue;
			}

			for (int i = 0; i < files.length; i++) {
				logFiles.put(fileIndex++, files[i].getPath());
			}
		}

		return logFiles;
	}

	public boolean isInitialized() {
		return initialized;
	}

	public LogViewerConfig getLogViewerConfiguration() {
		return logViewerConfiguration;
	}

	public Map<Integer, String> getLogFiles() {
		return logFiles;
	}

	public String getTailOfLogFile() {
		if (this.activeLogFileIndex == -1) {
			return "No content available";
		}
		setCurrentLogFileName(this.logFiles.get(activeLogFileIndex));
		File activeLogFile = new File(this.logFiles.get(activeLogFileIndex));
		ReverseLineReader reverseLineReader = new ReverseLineReader(activeLogFile, Charset.defaultCharset().name());
		try {
			List<String> logFileLastLines = reverseLineReader.readLastLines(this.displayLastLinesCount);
			
			StringBuilder sb = new StringBuilder();
			for (String logFileLastLine : logFileLastLines) {
				sb.append(logFileLastLine);
				sb.append('\n');
			}
			
			return sb.toString();
		} catch (IOException ex) {
			log.error("Failed to read log file '{}'", this.logFiles.get(activeLogFileIndex), ex);
			String result = String.format("Failed to read log file '%s'", this.logFiles.get(activeLogFileIndex));
			
			return result;
		} finally {
			try {
				reverseLineReader.close();
			} catch (IOException ex) {
				log.error("Failed to destory ReverseLineReader", ex);
			}
		}
	}

	public int getActiveLogFileIndex() {
		return activeLogFileIndex;
	}

	public void setActiveLogFileIndex(int activeLogFileIndex) {
		this.activeLogFileIndex = activeLogFileIndex;
		setCurrentLogFileName(this.logFiles.get(this.activeLogFileIndex));
	}


	public int getDisplayLastLinesCount() {
		return displayLastLinesCount;
	}

	public void setDisplayLastLinesCount(int displayLinesCount) {
		this.displayLastLinesCount = displayLinesCount;
	}

	public String getCurrentLogFileName() {
		return currentLogFileName;
	}

	public void setCurrentLogFileName(String currentLogFileName) {
		this.currentLogFileName = currentLogFileName;
	}
	
	

}

server/src/main/webapp/logviewer/configureLogViewer.xhtml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ox="http://xmlns.jcp.org/jsf/composite/ox"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:b="http://bootsfaces.net/ui"
	template="/WEB-INF/incl/layout/newtemplate.xhtml">
	<f:metadata>
		<f:viewAction
			action="#{permissionService.requestPermission('configuration', 'access')}" />
		<f:viewAction action="#{conversationService.initConversation}" />
		<f:viewAction action="#{configureLogViewerAction.init}"
			onPostback="false" />
	</f:metadata>

	<ui:define name="body">
		<section class="content-header">
			<h1 style="color: #333;">
				#{msgs['logViewer.configuration']} <small> <i
					class="fa fa-caret-right" style="color: #333 !important;" />
					#{msgs['logViewer.configureLogViewer']}
				</small>
			</h1>
			<ol class="breadcrumb">
				<li><a href="#{request.contextPath}/home.htm"> <i
						class="fa fa-home" />
				</a></li>
				<li class="organization/configuration"><a
					href="#{request.contextPath}/logviewer/configureLogViewer.htm">#{msgs['logViewer.configureLogViewer']}</a>
				</li>
			</ol>
		</section>
		<section class="content">
			<div id="formArea">
				<h:form id="logViewerForm">
					<f:validateBean>
						<b:panel title="LogViewer Configuration" look="primary"
							collapsible="false" iconAwesome="fa-ge">
							<div style="display: inline-block; width: 100% !important;">
								<h:panelGroup>
									<div class="row"
										style="padding: 5px; margin-bottom: 5px; margin-left: 0px">
										<ox:decorate forId="oxTrustLogConfigLocation"
											label="oxTrust External log4j location">
											<h:inputText id="oxTrustLogConfigLocation"
												class="form-control oxTrustLogConfigLocation"
												style="margin-right:5px;margin-bottom:10px;width:100%;float:left;"
												value="#{configureLogViewerAction.oxTrustLogConfigLocation}"></h:inputText>
										</ox:decorate>
									</div>
									<div class="row"
										style="padding: 5px; margin-bottom: 5px; margin-left: 0px">
										<ox:decorate forId="oxTrustLogConfigLocation"
											label="oxAuth External log4j location">
											<h:inputText id="oxAuthLogConfigLocation"
												class="form-control oxAuthLogConfigLocation"
												style="margin-right:5px;margin-bottom:10px;width:100%;float:left;"
												value="#{configureLogViewerAction.oxAuthLogConfigLocation}"></h:inputText>
										</ox:decorate>
									</div>
								</h:panelGroup>
							</div>
							<div class="box-footer">
								<div id="updateButtons">
									<h:commandButton action="#{configureLogViewerAction.update}"
										styleClass="btn btn-primary addLogButtonClass"
										value="#{msgs['logViewer.update']}" />
									<h:commandButton action="#{configureLogViewerAction.cancel}"
										immediate="true" style="margin-left:5px"
										styleClass="btn btn-primary"
										value="#{msgs['logViewer.cancel']}" />
								</div>
							</div>
						</b:panel>
					</f:validateBean>
				</h:form>
			</div>
		</section>
	</ui:define>
</ui:composition>

server/src/main/webapp/logviewer/viewLogFile.xhtml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:ox="http://xmlns.jcp.org/jsf/composite/ox"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	template="/WEB-INF/incl/layout/newtemplate.xhtml">
	<f:metadata>
		<f:viewAction
			action="#{permissionService.requestPermission('log', 'access')}" />
		<f:viewAction action="#{conversationService.initConversation}" />
		<f:viewAction action="#{viewLogFileAction.init}" onPostback="false" />
	</f:metadata>

	<ui:define name="head">
		<style type="text/css">
.overflowed {
	overflow-x: scroll;
}
</style>
	</ui:define>
	<ui:define name="body">
		<section class="content-header">
			<h1 style="color: #333;">
				#{msgs['logViewer.configuration']} <small> <i
					class="fa fa-caret-right" style="color: #333 !important;" />
					#{msgs['logViewer.viewLogFile']}
				</small>
			</h1>
			<ol class="breadcrumb">
				<li><a href="#{request.contextPath}/home.htm"> <i
						class="fa fa-home" />
				</a></li>
				<li class="organization/configuration"><a
					href="#{request.contextPath}/logviewer/viewLogFile.htm">#{msgs['logViewer.viewLogFile']}</a>
				</li>
			</ol>
		</section>
		<section class="content">
			<div id="formArea">
				<b:panel id="panelId" title="#{msgs['logViewer.viewLogFile']}" look="primary"
					iconAwesome="fa-file-archive-o" collapsible="false">
					<h:form id="logViewForm">
						<f:validateBean>
							<input name="cid" type="hidden" value="#{conversation.id}" />
							<div class="row">
								<div class="col-xs-12">
									<div class="nav-tabs-custom" style="margin-bottom: 0px;">
										<ul class="nav nav-tabs" id="logViewFormtab">
											<li class="active"><a data-toggle="tab"
												href="#logged-files">#{msgs['logViewer.allowedLogFiles']}</a>
											</li>
											<li><a data-toggle="tab" href="#config">#{msgs['logViewer.configuration']}</a>
											</li>
											<li><a data-toggle="tab" href="#tail">#{msgs['logViewer.tailOfLogFile']}</a>
											</li>
										</ul>
										<div class="tab-content">
											<div class="tab-pane active" id="logged-files">
												<div style="display: inline-block; width: 100% !important;">
													<rich:panel bodyClass="noPadding" id="MainBlock"
														header="Allowed log files" width="100%">
														<h:panelGroup border="0" cellpadding="0" cellspacing="0"
															columns="1" width="100%" id="PanelGroupId">
															<a4j:repeat
																value="#{viewLogFileAction.logFiles.entrySet().toArray()}"
																var="_logFile">
																<div class="filesContentBox">
																	<a4j:commandLink
																		action="#{viewLogFileAction.setActiveLogFileIndex(_logFile.key)}"
																		execute="@form" limitRender="true"
																		onclick="$('.nav-tabs a[href=\'#tail\']').tab('show');"
																		render="viewLogPanelId" value="#{_logFile.value}" />
																</div>
																<br />
															</a4j:repeat>
														</h:panelGroup>
													</rich:panel>
												</div>
											</div>
											<div class="tab-pane" id="config">
												<div style="display: inline-block; width: 100% !important;">
													<h:panelGroup>
														<ox:decorate
															label="#{msgs['logViewer.displayLastLinesCount']}">
															<h:inputText required="true" styleClass="form-control"
																value="#{viewLogFileAction.displayLastLinesCount}" />
														</ox:decorate>
													</h:panelGroup>
												</div>
											</div>
											<div class="tab-pane" id="tail">
												<div style="display: inline-block; width: 100% !important;">
													<h:panelGroup id="viewLogPanelId" layout="block">
														<h1>#{viewLogFileAction.getCurrentLogFileName()}</h1>
														<pre>
                                                     <h:outputText
																value="#{viewLogFileAction.getTailOfLogFile()}" />
                                                     </pre>
														<h1>#{viewLogFileAction.getCurrentLogFileName()}</h1>
													</h:panelGroup>
												</div>
											</div>
										</div>
									</div>
									<script>
										$('#logViewFormtab a').click(
												function(e) {
													e.preventDefault();
													$(this).tab('show');
												});
										$("ul.nav-tabs > li > a")
												.on(
														"shown.bs.tab",
														function(e) {
															var id = $(e.target)
																	.attr(
																			"href")
																	.substr(1);
															window.localStorage
																	.setItem(
																			'logViewFormtab',
																			id);
															var storeValue = window.localStorage
																	.getItem('logViewFormtab');
														});

										$(document)
												.ready(
														function() {
															var value = window.localStorage
																	.getItem('logViewFormtab');
															if (value) {
																var activeTab = "#";
																activeTab = activeTab
																		.concat(value);
																$(
																		'#logViewFormtab a[href="'
																				+ activeTab
																				+ '"]')
																		.tab(
																				'show');
															}
														});
									</script>
								</div>
							</div>
						</f:validateBean>
					</h:form>
				</b:panel>
			</div>
		</section>
	</ui:define>
</ui:composition>